config/routes.rb
Rails.application.routes.draw do
  resources :candies
  resources :kids
  

  root 'static_pages#index'
  match '/instructions', to: 'static_pages#instructions', via: 'get'

end

app/models/candy.rb
class Candy < ActiveRecord::Base
  has_and_belongs_to_many :kids
end

app/models/kid.rb
class Kid < ActiveRecord::Base
  has_and_belongs_to_many :candies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candies_controller.rb
class CandiesController < ApplicationController
  before_action :set_candy, only: [:show, :edit, :update, :destroy]

  # GET /candies
  # GET /candies.json
  def index
    @candies = Candy.order('lower(name)').all
  end

  # GET /candies/1
  # GET /candies/1.json
  def show
  end

  # GET /candies/new
  def new
    @candy = Candy.new
    @kids = Kid.order('lower(name)').all
  end

  # GET /candies/1/edit
  def edit
    @kids = Kid.order('lower(name)').all
  end

  # POST /candies
  # POST /candies.json
  def create
    @candy = Candy.new(candy_params)

    respond_to do |format|
      if @candy.save
        format.html { redirect_to @candy, notice: 'Candy was successfully created.' }
        format.json { render :show, status: :created, location: @candy }
      else
        format.html { render :new }
        format.json { render json: @candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candies/1
  # PATCH/PUT /candies/1.json
  def update
    respond_to do |format|
      if @candy.update(candy_params)
        format.html { redirect_to @candy, notice: 'Candy was successfully updated.' }
        format.json { render :show, status: :ok, location: @candy }
      else
        format.html { render :edit }
        format.json { render json: @candy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candies/1
  # DELETE /candies/1.json
  def destroy
    @candy.destroy
    respond_to do |format|
      format.html { redirect_to candies_url, notice: 'Candy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candy
      @candy = Candy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candy_params
      params.require(:candy).permit(:name, :kid_ids => [])
    end
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
  end

  # GET /kids/new
  def new
    @kid = Kid.new
    @candies = Candy.all
  end

  # GET /kids/1/edit
  def edit
    @candies = Candy.all
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(kid_params)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully created.' }
        format.json { render :show, status: :created, location: @kid }
      else
        format.html { render :new }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1
  # PATCH/PUT /kids/1.json
  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { render :show, status: :ok, location: @kid }
      else
        format.html { render :edit }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to kids_url, notice: 'Kid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_kid
    @kid = Kid.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def kid_params
    params.require(:kid).permit(:name, candy_ids: [])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candies_helper.rb
module CandiesHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/candies/_form.html.erb
<%= form_for(@candy) do |f| %>
  <% if @candy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candy.errors.count, "error") %> prohibited this candy from being saved:</h2>

      <ul>
      <% @candy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<hr />
  <div class="row">
    <div class="col-sm-4 checkbox-list">

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>
    </div>
    <div class="col-sm-6 checkbox-list">
      <p>
        <h4>Children</h4>
      </p>
      <div class="field">
        <%= collection_check_boxes(:candy, :kid_ids, @kids, :id, :name) %>
      </div>
    </div>
  </div> <!-- Row end -->
  <hr />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candies/edit.html.erb
<h1>Editing Candy</h1>

<%= render 'form' %>

<%= link_to 'Show', @candy %> |
<%= link_to 'Back', candies_path %>

app/views/candies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Candies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Kids</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candies.each do |candy| %>
      <tr>
        <td><%= candy.name %></td>
        <td><%= candy.kids.map {|k| k.name}.join(', ') %></td>
        <td><%= link_to 'Show', candy %></td>
        <td><%= link_to 'Edit', edit_candy_path(candy) %></td>
        <td><%= link_to 'Destroy', candy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />
<p>
  Add: <%= link_to 'New Candy', new_candy_path %><br />
  Go to: <%= link_to 'Kids', kids_path %>
</p>

app/views/candies/new.html.erb
<h1>New Candy</h1>

<%= render 'form' %>

<%= link_to 'Back', candies_path %>

app/views/candies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @candy.name %>
</p>
<p>
  <strong>Kids Names:</strong>
  <%= @candy.kids.map {|k| k.name}.join(', ') %>
</p>
<%= link_to 'Edit', edit_candy_path(@candy) %> |
<%= link_to 'Back', candies_path %>

app/views/kids/_form.html.erb
<%= form_for(@kid) do |f| %>
  <% if @kid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kid.errors.count, "error") %> prohibited this kid from being saved:</h2>

      <ul>
      <% @kid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col-sm-4 checkbox-list">

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

  </div>
  <div class="col-sm-6 checkbox-list">
    <p>
      <h4>Candies</h4>
    </p>
    <div class="field">
      <%#= collection_check_boxes(:kid, :candy_ids, @candies, :id, :name) %>
    </div>
    <%= collection_check_boxes(:kid, :candy_ids, @candies, :id, :name) %>
  </div>
</div> <!-- Row end -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kids/edit.html.erb
<h1>Editing Kid</h1>

<%= render 'form' %>

<%= link_to 'Show', @kid %> |
<%= link_to 'Back', kids_path %>

app/views/kids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kids</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Candies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kids.each do |kid| %>
      <tr>
        <td><%= kid.name %></td>
        <td><%= kid.candies.map {|c| c.name}.join(', ') %></td>
        <td><%= link_to 'Show', kid %></td>
        <td><%= link_to 'Edit', edit_kid_path(kid) %></td>
        <td><%= link_to 'Destroy', kid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr />
<p>
  Add: <%= link_to 'New Kid', new_kid_path %><br />
  Go to: <%= link_to 'Candy', candies_path %>
</p>

app/views/kids/new.html.erb
<h1>New Kid</h1>

<%= render 'form' %>

<%= link_to 'Back', kids_path %>

app/views/kids/show.html.erb
<!--<p id="notice"><%= notice %></p> -->

<p>
  <strong>Name:</strong>
  <%= @kid.name %>
</p>
<p>
  <strong>Candy Names:</strong>
  <%= @kid.candies.map {|c| c.name}.join(', ') %>
</p>
<%= link_to 'Edit', edit_kid_path(@kid) %> |
<%= link_to 'Back', kids_path %>

app/views/layouts/_footer.html.erb
<div>
  <footer class="footer">
    <hr />
    <p><%= link_to 'Home', root_path %></p>
    <hr />
    <small>
    <p>Created with a tutorial by <a href="http://www.britneywright.com">Britney Wright</a> - 2013</p>
    <p>Another Ruby on Rails App by <a href="http://mowen.imgd.ca/myweb/">Mike Owen</a>
    </p>
    </small>
  </footer>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- <div class="container-fluid"> -->
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">IMG 240 Learning Rails - HABTM</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
	      <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Instructions", instructions_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Kids", kids_path %></li>
			      <li><%= link_to "Candies", candies_path %></li>
            <li class="divider"></li>
            <li><a href="https://github.com/britneywright/habtm">Britney Wright's Github</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="http://sparc.nic.bc.ca/courses/content/img240">IMG240</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="http://sparc.nic.bc.ca/docs/ruby/">Ruby 2.3.0</a></li>
            <li><a href="http://guides.rubyonrails.org/">Rails Guides</a></li>
            <li><a href="http://sparc.nic.bc.ca/docs/ruby_core/">Ruby Core</a></li>
            <li class="divider"></li>
            <li><a href="https://bitbucket.org">Bitbucket</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Active App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="wrapper">
  <%= render "layouts/header" %>


    <div class="content">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/index.html.erb
<h1>This is an example of a has_and_belongs_to_many relationship in Rails 4</h1>
    <div class="well">
    <p>This Halloween inspired demo illustrates the relationships between kids who have many different candies and candies that are given out to many different kids.</p>
    <p>
    	<ul>
    		<li><a href="/kids">View Kids</a></li>
    		<li><a href="/candies">View Candies</a></li>
        <li><a href="/instructions">View Instructions</a></li>
    	</ul>
    </p>
    <p>You can also visit the <a href="https://github.com/britneywright/habtm">Github repo</a> to view all of the source code.</p>
</div>

app/views/static_pages/instructions.html.erb
<h1>habtm Rails 4 Example Instructions</h1>
<p>I'm taking the learning by doing approach to Ruby and Ruby on Rails by building an application. I'm creating an app that will have a directory of various resources people can use to learn to code.</p>

<p>As soon as I started, I ran into trouble trying to model my data. Some fields in my directory are straight forward like name and description, but others could contain multiple pieces of data in a single field, like programming language or difficulty level. For example a resource like Codecademy has lessons in multiple languages, including Ruby. And the reverse is also true, Ruby is taught by many resources, including Codecademy. In Rails this relationship is known as a has_and_belongs_to_many association. A resource has many languages and belongs to many languages.</p>

<p>After banging my head for two days and combing through loads of guides, books, and Stack Overflow questions I finally figured out how to use has_and_belongs_to_many (habtm) associations in Rails 4. Here's my step-by-step approach.</p>

<p>In the spirit of Halloween, my example involves kids and candy. Kids get a lot of different candy for halloween and candies go to a lot of different kids. Let's get started:</p>

<p>Let's get started in the command line. Execute each of the following lines: </p>

<pre><code></ul><li>rails new halloween </li>
<li>cd halloween</li>
<li>rails generate scaffold kid name</li>
<li>rails generate scaffold candy name</li>
<li>rails generate migration candies_kids</li>
</ul></code></pre>

<p>What's happening here? First, we create a new Rails application named "halloween" and move into it. Next, we're generating scaffolds for our kid and candy models, scaffolds set up common files with reasonable default code. We don't have to use scaffolds, but this will get us further along in the app so we can just focus on creating and executing the habtm association. Finally we create the database migration file for the candies kids join table. This is where the data shared between candy and kids is stored. It's important to note when naming the join table that you list the models alphabetically, so candies_kids, not kids_candies.</p>

<p>Now let's move from the command line to Sublime or the text editor of your choice. Add or edit the following lines of code in the indicated files:<p>

<h2>Models</h2>
- <a href= "https://github.com/britneywright/habtm/blob/master/app/models/candy.rb#L2">/app/models/candy.rb</a>
<pre class="prettyprint"><code>has_and_belongs_to_many :kids</code></pre>
<br>
- <a href = "https://github.com/britneywright/habtm/blob/master/app/models/kid.rb#L2">/app/models/kid.rb</a>
<pre class="prettyprint"><code>has_and_belongs_to_many :candies</code></pre>

<p>These lines of code declare the relationship between the models.</p>

<h2>Controllers</h2>
- /app/controllers/candies_controller.rb
	<p><a href="https://github.com/britneywright/habtm/blob/master/app/controllers/candies_controller.rb#L16-L24">create an instance variable in two places</a>
<pre class="prettyprint"><code>@kids = Kid.all</code></pre></p>

<p>
	<a href="https://github.com/britneywright/habtm/blob/master/app/controllers/candies_controller.rb#L74">in candy_params</a>
<pre class="prettyprint"><code>params.require(:candy).permit(:name, :kid_ids => [])</code></pre>
</p>
</p>
<br>
<p>
- /app/controllers/kids_controller.rb
<p><a href="ttps://github.com/britneywright/habtm/blob/master/app/controllers/kids_controller.rb#L16-L24">create an instance variable in two places</a><pre class="prettyprint"><code>@candies = Candy.all</code></pre>
</p>

<p>
<a href="https://github.com/britneywright/habtm/blob/master/app/controllers/kids_controller.rb#L74">in kids_params</a>
<pre class="prettyprint"><code>params.require(:kids).permit(:name, :candy_ids => [])</code></pre>
</p>

<p>This is one area where I got hung up. In Rails 3 you wouldn't need to update the controller, you would add "attr_accessible :name" to each model. However in Rails 4 we must use strong parameters, as attr_accessible has been extracted out of Rails. So in each of the controller files we add the attributes we're going to use from the opposing model, which in this case is the id field and the array of data that will be contained in it.</p>

<h2>Database</h2>
<p>Finally we need to manually edit the table we've started creating. We're going to create the candies_kids table with a field for the candy_id and a field for the kid_id. Those are the only two fields we need on the join table, so we'll tell Rails to not create an id for each entry. This is where :id => false comes into play.</p>
<p>
- <a href="https://github.com/britneywright/habtm/blob/master/db/migrate/20131030170256_candies_kids.rb#L2-L7">/db/TIMESTAMP_candies_kids.rb</a>
<pre class="prettyprint"><code>def change
  create_table :candies_kids, :id => false do |t|
    t.integer :candy_id
    t.integer :kid_id
  end
end</code></pre>
</p>

<p>Once you've updated the migration, go back into the command line and run the migration to create the table.
<pre><code><ul><li>rake db:migrate</li></ul></code></pre>
</p>

<p>The habtm relationship is now all set up. Let's look at two different ways to add data to the app. This is another area I had a hard time figuring out. Some exercises showed how to add data through the rails console, others only showed how part of one view should be set up. Here I've tried to show you a full 360 of adding and viewing the data.</p>

<p>In the command line use rails console to create new kids and candies. Then we can associate candies to kids and kids to candies.
<pre><code><ul><li>rails console</li>
<li>ashley = Kid.create!(:name => "Ashley")</li>
<li>snickers = Candy.create!(:name => "Snickers")</li>
<li>ashley.candies << snickers</li>
<li>timmy = Kid.create!(:name => "Timmy")</li>
<li>skittles = Candy.create!(:name => "Skittles")</li>
<li>skittles.kids << [timmy, ashley]</li></ul></p></code></pre>

<p>In order to view, add and edit the association data from within the app we need to make some file adjustments first. The scaffolds we created earlier already took care of creating the different views we'll use to see and edit the models, but they don't include the association data between the models yet. So back into the text editor we go:</p>
<h2>Views</h2>
- <a href="https://github.com/britneywright/habtm/blob/master/app/views/kids/index.html.erb#L18">/app/views/kids/index.html.erb</a>
<pre class="prettyprint"><code>&lt;th&gt;Candies&lt;/th&gt;
&lt;td&gt;&lt;%= kid.candies.map {|c| c.name}.join(', ') %&gt;&lt;/td&gt;</code></pre>

- <a href="https://github.com/britneywright/habtm/blob/master/app/views/candies/index.html.erb#L18">/app/views/candies/index.html.erb</a>
<pre class="prettyprint"><code>&lt;th&gt;Kids&lt;/th&gt;
&lt;td&gt;&lt;%= candy.kids.map {|k| k.name}.join(', ') %&gt;&lt;/td&gt;</code></pre>

- <a href="https://github.com/britneywright/habtm/blob/master/app/views/kids/show.html.erb#L8-L11">app/views/kids/show.html.erb</a>
<pre class="prettyprint"><code>&lt;p&gt;
  &lt;strong&gt;Candy Names:&lt;/strong&gt;
  &lt;%= @kid.candies.map {|c| c.name}.join(', ') %&gt;
&lt;/p&gt;</code></pre>

- <a href="https://github.com/britneywright/habtm/blob/master/app/views/candies/show.html.erb#L8-L11"/>app/views/candies/show.html.erb</a>
<pre class="prettyprint"><code>&lt;p&gt;
  &lt;strong&gt;Kids Names:&lt;/strong&gt;
  &lt;%= @candy.kids.map {|k| k.name}.join(', ') %&gt;
&lt;/p&gt;</code></pre>

<p>In the index.html.erb and show.html.erb files we use the map iterator to take the needed elements out of the data set and display each of their names separated by a comma and space. So in the case of Ashley based on what we added through the rails console we would see Snickers, Skittles in the app. Note the lines in the show.html.erb files call the instance variables, while the index.html.erb files are calling local variables since they are within blocks.</p>


- <a href="https://github.com/britneywright/habtm/blob/master/app/views/kids/_form.html.erb#L18-L20">/app/views/kids/_form.html.erb</a>
<pre class="prettyprint"><code>&lt;div class="field">
  &lt;%= collection_check_boxes(:kid, :candy_ids, @candies, :id, :name) %&gt;
&lt;/div&gt;</code></pre>

- <a href="https://github.com/britneywright/habtm/blob/master/app/views/candies/_form.html.erb#L18-L20">app/views/candies/_form.html.erb</a>
<pre class="prettyprint"><code>&lt;div class="field">
  &lt;%= collection_check_boxes(:candy, :kid_ids, @kids, :id, :name) %&gt;
&lt;/div&gt;</code></pre>

<p>In the _form.html.erb files, that are rendered in the edit and new pages, we create checkboxes for each option. We use the collection_check_boxes method to return check box tags for the collection of values. In the parentheses we include, in order, the object, method, collection, value_method, and text_method.</p>

<p>Finally, back in your command line:
<pre><code><ul><li>rails server</li></ul></code></pre>
</p>

<p>Now in your browser go to localhost:3000/kids or localhost:3000/candies. There you'll see the data we already added through the rails console. Here you can also create new kids and candies and assign them to each other.</p>

<p>And there you have it. You've just created a habtm relationship. Many thanks to <a href="http://twitter.com/josh_cheek">Josh Cheek</a> for his assistance with editing this post. I learned even more through the editing that I'll now use to update my own application. If you follow the steps in this post to set up a habtm relationship let me know how it goes. Did you find it clear? Is there anything you're still unsure about? I'd love to hear your thoughts.</p>

<p>Until next time,</p>

<p>Wright Said Fred</p>

<div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'habtmexample'; // required: replace example with your forum shortname
        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>